apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/service-name': 'backend'
        'consul.hashicorp.com/connect-service-protocol': 'http'
        'consul.hashicorp.com/service-meta-version': '1'
        'consul.hashicorp.com/service-tags': 'v1'
    spec:
      containers:
        - name: backend
          image: docker.io/ezraroi/backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            failureThreshold: 5 
            periodSeconds: 10
      serviceAccountName: backend
