apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend-deployment
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-protocol': 'http'
        'consul.hashicorp.com/service-name': 'frontend'
        'consul.hashicorp.com/service-meta-version': '1'
        'consul.hashicorp.com/service-tags': 'v1'
        'consul.hashicorp.com/connect-service-upstreams': 'backend:8080,backend-grpc:9090'
    spec:
      containers:
        - name: frontend
          image: docker.io/ezraroi/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            failureThreshold: 5 
            periodSeconds: 10
          envFrom:
            - configMapKeyRef:
                name: forntend-config-map
          env:
            - name: BACKEND_SERVICE_URL
              value: 'http://127.0.0.1:8080'
            - name: SPRING_CLOUD_CONSUL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      serviceAccountName: frontend
