apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-grpc-deployment
  labels:
    app: backend-grpc
spec:
  selector:
    matchLabels:
      app: backend-grpc
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-grpc
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/service-name': 'backend-grpc'
        'consul.hashicorp.com/connect-service-protocol': 'grpc'
    spec:
      containers:
        - name: backend-grpc
          image: index.docker.io/ezraroi/backend-grpc
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              name: grpc
      serviceAccountName: backend-grpc
