apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'frontend-service-load-balancer'
  namespace: 'default'
  labels:
    app: 'frontend-deployment'
spec:
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8081
  selector:
    app: 'frontend-deployment'
  type: 'NodePort'
  loadBalancerIP: ''
