apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  annotations:
    'consul.hashicorp.com/connect-inject': 'true'
spec:
  containers:
    - name: backend
      image: ezraroi/backend:0.0.1
      ports:
        - containerPort: 8080
          name: http
  serviceAccountName: backend
