apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: 'frontend'
  annotations:
    'consul.hashicorp.com/connect-inject': 'true'
    'consul.hashicorp.com/service-name': 'frontend'
    'consul.hashicorp.com/connect-service-upstreams': 'backend:8080,backend-grpc:9090'
spec:
  containers:
    - name: frontend
      image: ezraroi/frontend:0.0.1
      imagePullPolicy: Always
      ports:
        - containerPort: 8081
          name: http
      env:
        - name: BACKEND_SERVICE_URL
          value: 'http://localhost:8080'
        - name: SPRING_CLOUD_CONSUL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  serviceAccountName: frontend
---
apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'frontend-service-load-balancer'
  namespace: 'default'
  labels:
    app: 'frontend'
spec:
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8081
  selector:
    app: 'frontend'
  type: 'NodePort'
  loadBalancerIP: ''
