apiVersion: v1
kind: Secret
metadata:
  namespace: 'monitoring'
  name: grafana-creds
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4xMjM0
  GF_SECURITY_ADMIN_USER: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 'monitoring'
  generation: 1
  labels:
    app: grafana
  name: grafana
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: grafana-creds
        image: docker.io/grafana/grafana:5.3.2
        imagePullPolicy: IfNotPresent
        name: grafana
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'grafana'
  namespace: 'monitoring'
  labels:
    app: 'grafana'
spec:
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000
  selector:
    app: 'grafana'
  type: 'NodePort'
  loadBalancerIP: ''